### ISSUE TITLE
Kein Desktop-Icon

### ISSUE THREAD

**Issue by TB-archIT** [opsi4instituts/dfn_vlc#1]
Installer generiert leider automatisch ein Desktop-Icon. Leider ist mir kein Schalter bekannt, das zu unterdrücken.

Über ProductProperty 'desktopicon' sollte die Möglichkeit gegeben sein, das bei 'no' nachträglich löschen zu lassen.

**Comment by dorkmaneuver** [comment]
Das hab ich soweit eingebaut und ich würde jetzt einfach be allen dem System bekannten Usern durchgehen und das Icon löschen. Aber ich kenne mich mit Roaming Profiles nicht aus, Ihr scheint die einzusetzen. Muss ich da irgendwas beachten?

**Comment by TB-archIT** [comment]
? Icon wird doch unter 'C:\Users\Public\Desktop' angelegt. Muss ergo nur einmal gelöscht werden.

**Comment by dorkmaneuver** [comment]
Fixed
