### ISSUE TITLE
'custom' Verzeichnis

### ISSUE THREAD

**Issue by TB-archIT** [opsi4instituts/dfn_vlc#2]
Feature bitte einbauen, https://opsi.wzb.eu/wiki/index.php/%27custom%27_Verzeichnis

**Comment by dorkmaneuver** [comment]
Macht das nicht eher in Kombination mit ner Property Sinn? Warum brauchst Du das bei VLC? Für ein Settings-File (vlcrc)?

**Comment by TB-archIT** [comment]
Ist doch im Wiki beschrieben, dass zwei Properties eingerichtet werden!? Sollem ja auch defaultmäßig deaktiviert sein.

Ich brauche das für Programmverknüpfungen, an die unsere User gewöhnt sind. Deshalb sollte auch eine Variable mit dem Pfad zur Exe von VLC ($InstallDirExe$) definiert sein.

**Comment by dorkmaneuver** [comment]
Getan. Doch jetzt bekomme ich ein " Failed to execute package script 'postinst' of package '/var/lib/opsi/repository/dfn_vlc_2.2.1-1.opsi': Command '/tmp/.opsi.unpack.LxHP7/OPSI/postinst' failed (1):
Restoring previous directories...
Restoring previous custom dir...
Removing temporary files...
rm: cannot remove `/bin/bash': Permission denied"
Hast Du mir nen Tipp?

**Comment by TB-archIT** [comment]
Ups, das habe ich auch noch nie gehabt. Sind die Berechtigungen von 'postinst' ok? Nicht das beim Kopieren/Anlegen eine falsche Berechtigung das Ausführen verhindert.

**Comment by dorkmaneuver** [comment]
Habs gefunden. Nach 10 Stunden auf Arbeit noch Coden ist ne blöde Idee... :)
