### ISSUE TITLE
$ProductId$ synchronisieren

### ISSUE THREAD

**Issue by TB-archIT** [opsi4instituts/dfn_vlc#3]
Bislang haben wir ja nur in der 'control' die 'id' auf 'dfn_*' gesetzt, damit der Paketname das Prefix erhält.

Aus unserer Sicht ist es wichtig, dass die $ProductId$ in den OPSI-Skripten synchron dazu ist. 

Siehe auch https://opsi.wzb.eu/wiki/index.php/Existierendes_Paket_mit_dfn_Prefix_versehen

**Comment by dorkmaneuver** [comment]
Ach, stimmt, da wollte ich mit Dir gestern noch darüber reden. Es ist zwar alles doch recht lose gekoppelt, und in der Lizenzverwaltung ist dann ja der Pool nochmal extra bezeichnet, aber von der internen Logik find ich es gut, da bei z.b. vlc zu bleiben, oder sagen wir mal endnote. Dann heisst das Logo endnote.png, der holt sich die Lizenz aus dem Endnote-Pool, der p_endnote heisst, und so könnten auch zwei Endnote-Pakete sich den selben Lizenzpool teilen - der wahrschienlichere Fall als dass jedes Paket ein extra Pool hat. Zumindest bei uns im Haus. Daher würde ich die Prefixe nicht intern im Paket nutzen. Oder spricht da was eher dafür, was ich nicht sehe?

**Comment by dorkmaneuver** [comment]
stimmt, besser das auf github, dann können alle interessierten mitreden. :)

Am 06.08.2015 um 11:39 schrieb opsi-archIT-KIT:
> Bislang haben wir ja nur in der 'control' die 'id' auf 'dfn_*' gesetzt,
> damit der Paketname das Prefix erhält.
>
> Aus unserer Sicht ist es wichtig, dass die $ProductId$ in den
> OPSI-Skripten synchron dazu ist.
>
> Siehe auch
> https://opsi.wzb.eu/wiki/index.php/Existierendes_Paket_mit_dfn_Prefix_versehen
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/opsi4instituts/dfn_vlc/issues/3>.
>

-- 
======================================================

Eric Esser
DV-Koordination / IT Department
Betriebsratsmitglied
Wissenschaftszentrum Berlin
fuer Sozialforschung gGmbH

Reichpietschufer 50
10785 Berlin
Germany

Fon : ++49-30-25491-585
Fax : ++49-30-25491-558
Mail: eric.esser@wzb.eu

Service:
Di/Tue  9:00-17:30
Mi/Wed  9:30-17:30
Do/Thu  9:30-17:30

I'd go through life
With nonchalance and insouciance
If it weren't for making a living
Which is rather a nousciance

======================================================

**Comment by TB-archIT** [comment]
Ich habe konkret das Problem, dass über 'custom' wir einen
Webservicecall ausführen, um die Softwarekategorie zu dem Produkt
herauszufinden.

Und hier findet er halt dann mit dem Suchbegriff 'vlc' (= Produktid in
den Skripten) nicht das Produkt auf dem OPSI-Server (= dfn_vlc).

Klar könnte man jetzt überlegen nach 'vlc' zu suchen, aber irgendwann
kommt ein Paket, in dem die Buchstabenkombination auch enthalten ist,
dann gehen die Probleme wieder los.

**Comment by TB-archIT** [comment]
Mit %installingProdname% (der Dank für den Tipp geht an Detlef!) kann ich auf die 'product_id' aus 'control' zugreifen, somit ist das Problem für mich gelöst. Die Divergenz zu $ProductId$ in den Skripten kann bleiben.

Es bleibt natürlich das 'Problem', dass es für OPSI-Paket-Neueinsteiger verwirrend sein kann, dass die Werte, die eigentlich dasselbe meinen, unterschiedlich sind ;-)
