### ISSUE TITLE
Popup (Update & Network Access) unterdrücken

### ISSUE THREAD

**Issue by TB-archIT** [opsi4instituts/dfn_vlc#4]
Ich finde Popups beim ersten Start einer Software nicht gut, der User wird immer einfach mit den Defaulteinstellungen 'wegdrücken'.

Bedeutet bei VLC, dass "Netzwerkzugriff auf die Metadaten erlauben" sowie "Regelmäßig auf Aktuaisierungen für VLC prüfen" aktiviert sein wird. Ist IMO beides nicht gut.

Lösung!? Gibt es allerdings nicht systemweit (und Entwickler wollen das Problem nicht sehen), sondern nur via Userprofil (Stichwort vlcrc), siehe auch:
http://eddiejackson.net/wp/?p=4614
https://trac.videolan.org/vlc/ticket/9667

Via vlcrc müssen "qt-updates-notif" bzw. "metadata-network-access" entsprechend gesetzt sein.

Da 'User Profile Management' ja mittlerweile frei erhältlich ist, könnte man das darüber jedem User unterjubeln. Fraglich bleibt, was bei Usern passiert, wenn diese das Modul nicht aktiviert haben. Müsste mal getestet werden.

**Comment by TB-archIT** [comment]
Bzgl. 'login.opsiscript' ohne Modul 'User Profile Management': bei 'notepadpp' ist das getestet worden: es wird einfach ignoriert.

**Comment by dorkmaneuver** [comment]
Und wenn man einfach unter C:\Users\Default\AppData\Roaming\vlc diese Datei ablegt? Und die existierenden User noch mit einem Switch durchläuft? Finde ich besser, als das User Profile Management zwingend vorauszusetzen. Werde mir das kommende Woche mal anschauen und berichten...

**Comment by TB-archIT** [comment]
Wenn das funktioniert, ok.

Aber nochmal: 'User Profile Management' wäre deswegen keine zwingende Voraussetzung! Sofern das Modul eingerichtet wäre, wird es genutzt, falls nicht, einfach ignoriert und weiter gemacht.

**Comment by TB-archIT** [comment]
Nochmal über deinen alternativen Vorschlag nachgedacht. Der kann IMO in Umgebungen mit "Roaming Profile" nicht funktionieren. "Default" erhalten ja nur neue User, ein wanderndes Profil ist aber kein neuer User und mit dem "Switch" (auch wenn ich nicht weiß, was du genau damit meinst) erwischt du die ja auch nicht, weil bei uns z.B. das Profil nur lokal vorliegt, wenn der User wirklich eingeloggt ist.

**Comment by dorkmaneuver** [comment]
Mit Switch meinte ich so etwas wie /AllNtUserProfiles. Aber ich habe mit Roaming Profile gar keine Erfahrung, weil wir das hier nicht einsetzen. Magst nicht Du einfach den Fix dazu bauen? Du kannst es wenigstens testen, ob es mit den Roaming Profiles auch funktioniert... :)

**Comment by TB-archIT** [comment]
alles klar, mach ich

**Comment by TB-archIT** [comment]
Alles in Paket dfn_vlc_2.2.1-3.opsi eingebaut.
